### ISSUE TITLE
Day 4: `upstream` is more idiomatic

### ISSUE THREAD

**Issue by ramanshah** [ramanshah/intermediate_git#5]
@gaow pointed out that it's more idiomatic among users of the fork workflow to fork a project first and have the fork be `origin` with the original project being called `upstream`.

Fixing this will be a lot of work - will need to completely re-do the fork model flipbook in addition to the activity instructions - but potentially worth it.

**Comment by ramanshah** [comment]
Fixed this finally! Thanks @gaow for the reviewing comments.

**Comment by gaow** [comment]
Great to see it happen -- solid work @ramanshah!
